### PR TITLE
Enhancement/tests

### PR DESCRIPTION
**Pull request by jackboberg**
Attempts to use a docker container to create integration tests.

### CODE REVIEW

**Comment by jackboberg** [comment]
tests timed out on node `4.x`, but re-running them passed. I will update README with docs about testing and try another push...

**Comment by franvarney** [comment]
what's the status on this?

**Comment by jackboberg** [comment]
have not done the `README` stuff... :(

**Comment by jackboberg** [comment]
Rebased, with updated docker config. I'm now using Docker for Mac locally, instead of `dlite`.

**Comment by jackboberg** [comment]
😢 these tests are passing locally, trying to look into why travis fails

**Comment by theworkflow** [comment]
@jackboberg tests are now passing 😄

**Comment by jackboberg** [comment]
I just had to rerun them, but it's the second time that's happened. I'm not excited about the idea of introducing a test suite that _usually_ passes.

**Comment by jackboberg** [comment]
rebased and standardized

**Pull request merged**
